server:
  port: 8899
  path: "localhost:"
  protocol: http://

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playgrounds?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    database: mysql


  jackson:
    serialization:
      INDENT_OUTPUT: true

flyway:
  locations: classpath:/flyway
  encoding: utf8

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
api:
  path: /api

mail:
  from: rezervisiTermin@gmail.com
  body: "<H2>Molimo Vas potrvrdite registraciju klikom na link:</H2>"
  afterConfirmLoginUrl: "http://localhost:4200"
  registration:
        subject: "Potvrda registracije"
  confirmUser:
        path: "/confirm?"
  resetPass:
        path: "/reset?"

scheduler:
  delay: 10000
