server:
  port: 8899
  path: "localhost:"
  protocol: http://


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/terms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql

  profiles:
    active: dev

flyway:
  locations: classpath:/flyway
  encoding: utf8

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
api:
  path: /api

mail:
  from: rezervisiTermin@gmail.com
  body: "<H2>Molimo Vas potrvrdite registraciju klikom na link:</H2>"
  changePasswordBody: "<H2>Molimo Vas potrvrdite promjenu password-a klikom na link:</H2>"
  afterConfirmLoginUrl: "http://localhost:4200"
  registration:
        subject: "Potvrda registracije"
  changePassword:
        subject: "Ažuriranje password-a"
  confirmUser:
        path: "/confirm?"
  resetPass:
        path: "/reset?"

scheduler:
  delay: 10000
